
reviewers:
  # The default reviewers
  defaults:
    - repository-owners # group

# Reviewer groups each of which has a list of GitHub usernames
  groups:
    repository-owners:
      - bjohnsto
#      - jochapman
#      - jshimkus-rh
