name: PR Created

on:
  pull_request_target:
    types: [ opened, reopened, ready_for_review ]

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
    
