name: Notify Slack
on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: string
      pr-text:
        required: true
        type: string
      pr-link:
        required: true
        type: string
jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    steps:
    - name: Send Message
      shell: bash
      run: |
          curl -X POST \
          --header 'content-type: application/json' \
          --url "${{ secrets.NOTIFY_URL }}" \
          --data '{ \
           PR_ID: 15, \
           "BODY": "This is some text", \
           }'
