name: Notify Slack
on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: number
      pr-text:
        required: true
        type: string
      pr-link:
        required: true
        type: string
jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    steps:
    - name: Send Message
      shell: bash
      run: |
          curl --request POST \
          --header 'content-type: application/json' \
          --url ${{ secrets.SLACK_URL }} \
          --data '{ \
           "PR_ID": "${{ inputs.pr-number }}", \
           "BODY": ${{ inputs.pr-text }}", \
           }'
