name: Notify Slack
on:
  pull_request_target:
    types: [ labeled ]
    branches: [ main ]

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: Send a message to Slack
    steps:
      - name: addlabel
        run: echo Starting
