name: Test Labelling a pull request
on:
  pull_request_target:
    types: [ labeled ]
    branches: [ main ]

jobs:
  approved:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "This PR was approved Step 1"
        
      - name: addLabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: merged
          type: add
      
      - name: removeLabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: approved
          type: remove
          
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.NOTIFY_URL }}
        run: |
          curl --request GET \
          --header 'content-type: application/json' \
          --url "$SUPER_SECRET" \
          --data '{
            "PR_ID": "${{github.event.inputs.pr_num }}",
            "BODY": "This is some test text!",
          }'        
