name: Test Labelling a pull request
on:
  pull_request_target:
    types: [ labeled ]
    branches: [ main ]

jobs:
  approved_label:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "This PR was approved Step 1"
        
      - name: addLabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: merged
          type: add
      
      - name: removeLabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: approved
          type: remove
          
      - name: sendSlack
        uses: .github/workflows/notify-slack.yml@main
        with:
          pr-number: 16
          pr-text: "This is some text!"
          pr-link: ""
      
          
