name: Test Labelling a pull request
on:
  pull_request_target:
    types: [ labeled ]
    branches: [ main ]

jobs:
  send_notification:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    uses: ./.github/workflows/notify-slack.yml
      with:
        pr-number: 16
        pr-text: "This is some text!"
        pr-link: ""
      secrets:
        token: ${{ secrets.GITHUB_TOKEN }}
      
          
