name: PR Created

on:
  pull_request_target:
    types: [ opened, reopened, ready_for_review ]

jobs:
  set_labels:  
    runs-on: ubuntu-latest
    steps:
      - uses: jamessingleton/is-organization-member@v1
        with:
          organization: TheSafetyDanceFanClub
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.is_organization_member.outputs.result == 'false' }}          
        run: echo User Does Not Belong to TheSafetyDanceFanClub
