name: PR Created

on:
  pull_request_target:
    types: [ opened, reopened, ready_for_review ]

jobs:
  handle_pr_start:  
    runs-on: ubuntu-latest
    steps:
      - name: Check for org membership
        id: is_organization_member
        uses: jamessingleton/is-organization-member@1.0.0
        with:
          organization: TheSafetyDanceFanClub
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}              
      - name: Add external contrib label
        if: ${{ steps.is_organization_member.outputs.result == 'false' }}
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.RUNPRLABEL}}
          label: verification needed
          type: add     
      - name: Add internal contrib label
        if: ${{ steps.is_organization_member.outputs.result == 'true' }}
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.RUNPRLABEL}}
          label: untested
          type: add     
      - name: Send message
        if: ${{ steps.is_organization_member.outputs.result == 'false' }}
        uses: ./.github/workflows/notify-slack.yml
        with:
          pr-number: ${{ github.event.pull_request.number }}
          pr-text: ${{ github.event.pull_request.title }}
          pr-link: ${{ github.event.pull_request.url }}   
          token: ${{ secrets.NOTIFY_URL }}        
