name: PR Created

on:
  pull_request_target:
    types: [ opened, reopened, ready_for_review ]

jobs:
  set_labels:  
    runs-on: ubuntu-latest
    steps:
      -  uses: tspascoal/get-user-teams-membership@v2
         id: checkUserMember
         with:
          username: ${{ github.actor }}
          team: 'vdo'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'false' }}
        
          
