name: Test Labelling a pull request 2
on:
  pull_request_target:
    types: [ labeled ]
    branches: [ main ]

jobs:
  approved:
    if: github.event.label.name == 'merged'
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "This PR was merged Step 1"
              
      - name: removeLabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: merged
          type: remove
