name: PR private test

on:
  pull_request_target:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == "public testing done" }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Start testing
      run: echo Private Testing Start

    - name: add testing running label
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: private testing running
        type: add

    - name: remove untested label
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: public testing done
        type: remove
        
    - name: Run-Untrusted-Tests
      # run: make jenkins
      run: |
        sleep 30
        exit 0
    
    - name: remove public testing running
      if: always()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: private testing running
        type: remove

    - name: Add private testing failed
      if: failure()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: private testing failed
        type: add
        
    - name: Add private testing done
      if: success()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: private testing done
        type: add
        
