name: PR CI

on:
  pull_request_target:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'untested' }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Start testing
      run: echo Testing Start

    - name: add testing running label
      uses: buildsville/add-remove-label@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: public testing running
        type: add

    - name: remove untested label
      uses: buildsville/add-remove-label@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: untested
        type: remove
        
    - name: Run-Untrusted-Tests
      run: make jenkins
    
    - name: Add public-testing failed
      if: failure()
      uses: buildsville/add-remove-label@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: public testing failed
        type: add
        
    - name: remove untested label
      uses: buildsville/add-remove-label@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: public testing running
        type: remove
