name: Run Public Tests

on:
  workflow_call:

jobs:
  runPublicTests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Start testing
      run: echo Testing Start

    - name: add testing running label
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: public testing running
        type: add

    - name: remove untested label
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: untested
        type: remove
        
    - name: Run-Untrusted-Tests
      run: make jenkins
      # run: |
      #  sleep 30
      #  exit 0
    
    - name: remove public testing running label
      if: always()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: public testing running
        type: remove

    - name: Add public testing failed
      if: failure()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: public testing failed
        type: add
        
    - name: Upload artifact
      if: failure()
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      with:
        files: common/logs/**/*.xml
    
    - name: Prepare Logfiles
      if: failure()
      run: |  
        cd common/logs/perltests
        for file in *.log;
        do
          mv ${file} ${file/::/--}
        done

    - name: Upload artifact
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: Upload Test Logs
        path: common/logs/perltests/*.log
        retention-days: 5

    - name: Add public testing success
      if: success()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.RUNPRLABEL}}
        label: public testing done
        type: add
