name: Run Private Tests

on:
  pull_request_target:
    types: [ labeled ]
  workflow_call:

jobs:
  runPrivateTests:
    if: ${{ github.event.label.name == 'public testing done' }}
    runs-on: [self-hosted, trusted]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Start Private testing
      run: echo Private Testing Start
      
    - name: add testing running label
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: private testing running
        type: add
        
    - name: Run-trusted-Tests
      run: make jenkins
      
    - name: Copy log file to /home/bunsen-home/artifacts
      if: always()
      run: |
        REPO=${{ github.repository }}
        REPO=${REPO//\//-}
        cp -a logs /home/bunsen-home/artifacts/logs.`date +'%Y%m%d%H%M'`.$REPO.${{ github.event.number }}
    
    - name: remove private testing running label
      if: always()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: private testing running
        type: remove

    - name: Add private testing failed
      if: failure()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: private testing failed
        type: add
        
    - name: Add private testing success
      if: success()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.RUNPRLABEL}}
        label: private testing done
        type: add
        
        
