name: Run Test
on:
  pull_request_review:
    types: [submitted]
    branches: [ main ]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: self-hosted
    steps:
      - name: step 1
        run: echo "This PR was approved Step 1"
        
      - name: addApproveLabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: public-testing-approve
          type: add
