name: Notify Slack on State Changes
on:
  pull_request_target:
    types: [ labeled, assigned, unassigned, review_requested, review_requested_removed ]
    branches: [ main ]

jobs:
  review_needed:
    if: ${{ github.event.action == "labeled" && github.event.label.name == "approved" }}
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "review needed label set"
        
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.NOTIFY_URL }}
        run: |
          curl -X POST \
          --header 'content-type: application/json' \
          --url "$SUPER_SECRET" \
          --data '{
            "PR_ID": "15",
            "BODY": "This is some test text!",
          }'        
