name: Notify Slack on State Changes
on:
  pull_request_target:
    types: [ labeled ]
    branches: [ main ]

jobs:
  pr_merged:
    if: ${{ github.event.action == "labeled" && github.event.label.name == "merged" }}
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "merged label set"
        
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.NOTIFY_URL }}
        run: |
          curl -X POST \
          --header 'content-type: application/json' \
          --url "$SUPER_SECRET" \
          --data '{
            "PR_ID": "15",
            "BODY": "This is some test text!",
          }'          
