name: Synchronize

on:
  workflow_run:
    workflows: ['Testing']
    types:
      - completed
  pull_request_target:
    types: [ synchronize ]

jobs:
  Code-Updated:  
    runs-on: ubuntu-latest
    steps:
    - name: Remove all known labels
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: untested, public testing running, public testing done, public testing failed, private testing running, private testing done, private testing failed
        type: remove
    - name: Check for org membership
      id: is_organization_member
      uses: jamessingleton/is-organization-member@1.0.0
      with:
        organization: TheSafetyDanceFanClub
        username: ${{ github.actor }}
        token: ${{ secrets.GITHUB_TOKEN }}              
    - name: Add internal contrib label
      if: ${{ steps.is_organization_member.outputs.result == 'true' }}
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.RUNPRLABEL}}
        label: untested
        type: add     
    - name: Add external contrib label
      if: ${{ steps.is_organization_member.outputs.result == 'false' }}
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.RUNPRLABEL}}
        label: verification needed
        type: add                       
