name: Testing

on:
  pull_request:
    types: [ labeled ]
  workflow_call:

jobs:
  Public-Testing:
    if: ${{ github.event.label.name == 'untested' }}
    runs-on: [self-hosted, untrusted]
    steps:

    - name: add testing running label
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: public testing running
        type: add
