name: Testing

on:
  pull_request_target:
    types: [ labeled ]
  workflow_call:

jobs:
  runPublicTests:
    if: ${{ github.event.label.name == 'untested' }}
    runs-on: [self-hosted, untrusted]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Start testing
      run: echo Testing Start

    - name: add testing running label
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: public testing running
        type: add

    - name: remove untested label
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: untested
        type: remove
        
    - name: Run-Untrusted-Tests
      # run: make jenkins
      run: |
        sleep 30
        exit 1
    
    - name: remove public testing running label
      if: always()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: public testing running
        type: remove

    - name: Add public testing failed
      if: failure()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: public testing failed
        type: add
        
    - name: Upload artifact
      if: failure()
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      with:
        files: logs/**/*.xml
    
    - name: Prepare Logfiles
      if: failure()
      run: |  
        cd logs/vdotests
        for file in *::*.log;
        do
          mv ${file} ${file/::/--}
        done

    - name: Upload artifact
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: Upload Test Logs
        path: logs/vdotests/*.log
        retention-days: 5

    - name: Add public testing success
      if: success()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: public testing done
        type: add

  runPrivateTests:
    runs-on: [self-hosted, trusted]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Start Private testing
      run: echo Private Testing Start
      
    - name: add testing running label
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: private testing running
        type: add
        
    - name: Run-trusted-Tests
      run: make jenkins
      
    - name: Copy log file to /home/bunsen-home/artifacts
      if: always()
      run: |
        REPO=${{ github.repository }}
        REPO=${REPO//\//-}
        cp -a logs /home/bunsen-home/artifacts/logs.`date +'%Y%m%d%H%M'`.$REPO.${{ github.event.number }}
    
    - name: remove private testing running label
      if: always()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: private testing running
        type: remove

    - name: Add private testing failed
      if: failure()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: private testing failed
        type: add
        
    - name: Add private testing success
      if: success()
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.RUNPRLABEL}}
        label: private testing done
        type: add
