name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #  branches: [ main ]
  # pull_request:
  #  branches: [ main ]
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Clone the Source tree
        run: git -c http.sslVerify=false clone https://gitlab.cee.redhat.com/vdo/open-sourcing/src/common.git
        
      - name: Prepare and Build Tree
        run: |
          cd common
          # Try to maintain 'pretty-ness' of the deferred tests.  Probably for no reason...
          sed -r -i '/^@deferred = /a \ \ \ \ \ \ \ \ \ \ \ \ "ArchiveLogs_t1", # Fails in testArchiveLogs' perl/Permabit/testcases/suites
          sed -r -i '/^@deferred = /a \ \ \ \ \ \ \ \ \ \ \ \ "CheckServer_t1", # Fails to run "getent netgroup resources"' perl/Permabit/testcases/suites
          sed -r -i '/^@deferred = /a \ \ \ \ \ \ \ \ \ \ \ \ "CheckDNSTrigger_t1", # Fails due to missing p4 binary' perl/Permabit/testcases/suites
          sed -r -i '/^@deferred = /a \ \ \ \ \ \ \ \ \ \ \ \ "P4Utils_t1", # Fails due to missing p4 binary' perl/Permabit/testcases/suites
          sed -r -i '/^@deferred = /a \ \ \ \ \ \ \ \ \ \ \ \ "ReserveHostGroup", # Has an issue leaking machines' perl/Permabit/testcases/suites
          sed -r -i '/^@deferred = /a \ \ \ \ \ \ \ \ \ \ \ \ "SSHMuxIPCSession_t1", # Unreaped children during testSigChild' perl/Permabit/testcases/suites
          sed -r -i '/^@deferred = /a \ \ \ \ \ \ \ \ \ \ \ \ "SystemUtils_t1", # fails to run "getent netgroup dev-critical' perl/Permabit/testcases/suites
          # P4.pm still needs to be removed currently because of a problem with the p4perl package.
          # Can't load '/usr/lib64/perl5/vendor_perl/auto/P4/P4.so' for module P4: /usr/lib64/perl5/vendor_perl/auto/P4/P4.so: undefined symbol: SSLeay at /usr/lib64/perl5/DynaLoader.pm line 193.
          # at ./P4.pm line 25.
          # Compilation failed in require at ./P4.pm line 25.
          # BEGIN failed--compilation aborted at ./P4.pm line 25.
          rm -f perl/Permabit/P4.pm
          make
        
      - name: Run common Tests (make jenkins)
        run: |
          cd common
          make jenkins
          
      - name: Run vdo-devel Tests (make jenkins)
        run: |
          make jenkins
      
      # Details for this step can be found here: https://github.com/marketplace/actions/publish-unit-test-results#support-fork-repositories-and-dependabot-branches    
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: common/logs/**/*.xml
    
    
      # Prepare logs to be archived.  Rename them to use '--' instead of '::' since the default spelling is disallowed by the upload-artifacts action.
      # We should try to scrub hostnames and other internal information if possible.
      - name: Prepare Logfiles
        if: failure()
        run: |
          cd common/logs/perltests
          for file in *.log;
          do
            mv ${file} ${file/::/--}
          done

      - name: Upload Logfiles
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Upload Test Logs
          path: common/logs/perltests/*.log
          retention-days: 5
