name: Setting reviewers and assignees

on:
  pull_request_target:
    types: [ opened, reopened, ready_for_review ]

jobs:
  Verifying-User:  
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewer
        uses: necojackarc/auto-request-review@v0.10.0
        with:
          token: ${{ secrets.RUNPRLABEL }}
